[language-server.clangd]
command = "clangd"
args = [ "--clang-tidy" ]

[language-server.typos]
command = "typos-lsp"
environment = {"RUST_LOG" = "error"}
# config.config = "~/code/typos-lsp/crates/typos-lsp/tests/typos.toml"
config.diagnosticSeverity = "Warning"

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c", "h"] # TODO: ["h"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "clangd", "typos" ]
indent = { tab-width = 2, unit = "  " }
